CREATE DATABASE `test` DEFAULT CHARACTER SET utf8;

GRANT SELECT,INSERT,UPDATE,DELETE
ON `test`.*
TO db_user@localhost
IDENTIFIED BY '781262Vadim!@';

GRANT SELECT,INSERT,UPDATE,DELETE
ON `test`.*
TO db_user@'%'
IDENTIFIED BY '781262Vadim!@';